#!/usr/bin/perl -I.
use CGI qw(:standard);
#use strict;
use HOP qw(insert_signature);

local(%in) = &parse_form;
local($sid,%cses,%cfg,%sys);
$in{'sid'} ? ($sid   = $in{'sid'}): ($sid   = '');

##### Loading File Location
# --------------------------------------------------------
open (CFG, "<../general.cfg") or &cgierr ("Unable to open: setup.cfg,150,$!");
LINE: while (<CFG>) {
	(/^#/)      and next LINE;
	(/^\s*$/)   and next LINE;
	$line = $_;
	$line =~ s/\n|\r//g;
	my ($td,$name,$value) = split (/\||\=/, $line,3);
	if ($td eq "conf") {
		$cfg{$name} = $value;
		next LINE;
	}elsif ($td eq "sys"){
		$sys{$name} = $value;
		next LINE;
	}
}
close CFG;

eval { &main; };
if ($@) { &cgierr("Fatal error",101,$@); }

exit;


sub main {
# --------------------------------------------------------
	print new CGI->header(-type=>"text/html");
	if ($in{'fromapp'} eq 'sales' and !$sys{'cc_verification_inb'}){
		$pre_approved = 1;
	}elsif(!$sys{'cc_verification'} and !$in{'fromapp'}){
		$pre_approved = 1;
	}

	if ($pre_approved){
		if (open(AUTH, ">$cfg{'auth_dir_cc'}$sid")){
			print AUTH "decision=ACCEPT\n";
			print AUTH "ccauthreply_authorizationcode=0000\n";
			print AUTH "ccauthreply_authorizeddatetime=-----\n";
			print AUTH "########## PRE - APPROVED MODE !!!!!!\n";
		}
		close AUTH;	
		return;
	}


	#	if (open(AUTH, ">$cfg{'auth_dir_cc'}$sid")){
	#		print AUTH "decision=REJECT\n";
	#		print AUTH "ccauthreply_authorizationcode=0000\n";
	#		print AUTH "ccauthreply_authorizeddatetime=-----\n";
	#	}
	#	close AUTH;	
	#	return;
		
	if ($in{'return_cc'}){
		#print "<pre>\nForm Variables IN\n-------------------------------------------\n";
		#foreach $key (sort keys %in) {
		#	#my $space = " " x (20 - length($key));
		#	$out_in .= "$key=$in{$key},";
		#	print "$key$space: $in{$key}\n";
		#}
		if (open(AUTH, ">$cfg{'auth_dir_cc'}$sid")){
			foreach $key (sort keys %in) {
				print AUTH "$key=$in{$key}\n";
			}
		}
		close AUTH;
	}else{
		#print "sending info $sid";
		&load_callsession;
		$cses{'state'} = substr($cses{'state'},0,2);
		%cctype= ('Visa'=>'001','Mastercard'=>'002','American Express'=>'003','Discover'=>'004');

		#<option value="001">Visa
		#<option value="002">MasterCard
		#<option value="003">American Express
		#<option value="004">Discover
		$month = substr($cses{'pmtfield4'},0,2);
		$year  = 2000 + substr($cses{'pmtfield4'},2,4); 
		#$cses{'total_order'} = int($cses{'total_order'}*100+9)/100;

		#https://orderpagetest.ic3.com/hop/ProcessOrder.do
		#print "firstname : $cses{'firstname'}";
		#<body onload="self.document.cyberform.submit()">
		#<form action="https://orderpage.ic3.com/hop/ProcessOrder.do" method="post" name="cyberform">
		
		
		if ($cfg{'cd'}){
			print qq|
<html>
<body>
<form action="https://orderpagetest.ic3.com/hop/ProcessOrder.do" method="post" name="cyberform">\n|;
		}else{
			print qq|
<html>
<body onload="self.document.cyberform.submit()">
<form action="https://orderpage.ic3.com/hop/ProcessOrder.do" method="post" name="cyberform">\n|;
		}
		insert_signature("$cses{'total_order'}","usd");
		print qq|
<input type="hidden" name="RequestID" value="$cses{'id_orders'}">		
<input type="hidden" name="orderPage_transactionType" value="authorization">
<input type="hidden" name="billTo_firstName" value="$cses{'firstname'}">
<input type="hidden" name="billTo_lastName" value="$cses{'lastname1'}">
<input type="hidden" name="billTo_street1" value="$cses{'address1'}">
<input type="hidden" name="billTo_street2" value="$cses{'address2'}">
<input type="hidden" name="billTo_customerID" value="$cses{'id_customers'}">
<input type="hidden" name="billTo_city" value="$cses{'city'}">
<input type="hidden" name="billTo_state" value="$cses{'state'}">
<input type="hidden" name="billTo_postalCode" value="$cses{'zip'}">
<input type="hidden" name="billTo_country" value="US">
<input type="hidden" name="billTo_phoneNumber" value="$cses{'pmtfield6'}">
<input type="hidden" name="comments" value="$cses{'id_orders'}">
<input type="hidden" name="merchantReferenceCode" value="$cses{'id_orders'}">
<input type="hidden" name="card_cardType" value="$cctype{$cses{'pmtfield1'}}">
<input type="hidden" name="card_accountNumber" value="$cses{'pmtfield3'}">
<input type='hidden' name='card_cvNumber' value="$cses{'pmtfield5'}">
<input type="hidden" name="card_expirationMonth" value="$month">
<input type="hidden" name="card_expirationYear" value="$year">
<input type="hidden" name="sid" value="$sid">	
<input type="hidden" name="id_orders" value="$cses{'id_orders'}">	
<input type="hidden" name="id_customers" value="$cses{'id_customers'}">	
<input type="hidden" name="return_cc" value="1">\n|;
	if ($cfg{'cd'}){
			print qq|<input type="submit" value="submit">|;
	}
	print "</form>";
	}
}

sub load_callsession {
# --------------------------------------------------------
	open(AUTH, "<$cfg{'auth_dir'}/call$sid") or &cgierr("Unable to open file: $cfg{'auth_dir'}/call$sid",702,$!);
	LINE: while (<AUTH>) {
		$line = $_;
		$line =~ s/\r|\n//g;
		($line =~ /([^=]+)=(.*)/) or (next LINE);
		$cses{$1} = $2;
		$cses{$1} =~ s/~~/\n/g;
	}
	close AUTH;
	return;
}

sub parse_form {
# --------------------------------------------------------
	my (@pairs, %in);
	my ($buffer, $pair, $name, $value);

	if ($ENV{'REQUEST_METHOD'} eq 'GET') {
		@pairs = split(/&/, $ENV{'QUERY_STRING'});
	}
	elsif ($ENV{'REQUEST_METHOD'} eq 'POST') {
		read(STDIN, $buffer, $ENV{'CONTENT_LENGTH'});
 		@pairs = split(/&/, $buffer);
	}
	else {
		&cgierr ("This script must be called from the Web\nusing either GET or POST requests\n\n");
	}
	PAIR: foreach $pair (@pairs) {
		($name, $value) = split(/=/, $pair);

		$name =~ tr/+/ /;
		$name =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
		$name = lc($name);

		$value =~ tr/+/ /;
		$value =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;

		$value =~ s/^\s+//g;
		$value =~ s/\s+$//g;

		#$value =~ s/\r//g;
		if ($value eq "---") { next PAIR; }		# This is used as a default choice for select lists and is ignored.
		(exists $in{$name}) ?
			($in{$name} .= "|$value") :		# If we have multiple select, then we tack on
			($in{$name}  = $value);			# using the ~~ as a seperator.
	}
	return %in;
}

##################################################################
#     CGIERR   	#
##################################################################
sub cgierr {
# --------------------------------------------------------
# Last Modified on: 11/10/08 12:35:27
# Last Modified by: MCC C. Gabriel Varela S: Se corrige el formato de la fecha
	my (@sys_err) = @_;
	print "Content-type: text/html\n\n";
	my ($key,$env,$out_in,$out_env);
	if (!$cfg{'cd'}){
		print qq|
					<head>
									<title>CGI - ERROR</title>
					</head>					
					<body BGCOLOR="#FFFFFF" LINK="#FF0000" VLINK="#FF0000" ALINK="#FF0000">
					
									<table BORDER="0" WIDTH="500" CELLPADDING="10" CELLSPACING="10">
									  <tr>
									    <td BGCOLOR="#FF0000" colspan="2"><font size="5" color="#FFFFFF" face="Arial"><b>CGI-Error</b></font></td>
									  </tr>
									</table>
									<table BORDER="0" WIDTH="550" CELLPADDING="2" CELLSPACING="0">|;
										$sys_err[0]	and print "\n<tr>\n  <td valign='top' width='200'><font face='Arial' size='3'>Error Message</font></td>\n  <td><font face='Arial' size='3' color='#FF0000'><b>$sys_err[0]</b></font></td>\n</tr>\n";
										$sys_err[1]	and print "<tr>\n  <td width='200'><font face='Arial' size='2'>Error Code</font></td>\n  <td><font face='Arial' size='2'>$sys_err[1]</font></td>\n";
										$sys_err[2]	and print "<tr>\n  <td valign='top' width='200'><font face='Arial' size='2'>System Message</font></td>\n  <td><font face='Arial' size='2'>$sys_err[2]</font></td>\n";
										print qq|
									<tr>
									  <td colspan="2"><p>&nbsp</p><font face='Arial' size='2'>If the problem percist, please contact us with the above Information.</font><br>
											<font face='Arial' size='2'><a href="mailto:$systememail">$systememail</a></font></td>
									</tr>
									  </table>
					</body>
					</html>|;
		######################################
		### Save CGI ERR			
		##############################
		my ($ip);
		my (@outmsg) = @sys_err;
		my ($sec, $min, $hour, $day, $mon, $year, $dweek, $dyear, $daylight) = localtime(time());
		$year+=1900;
		$mon++;
		my ($time,$date) = ("$hour:$min:$sec","$mon-$day-$year");
		
		foreach $key (sort keys %in) {
			$outmsg[3] .= "$key=$in{$key},";
		}
		
		foreach $env (sort keys %ENV) {
			$outmsg[4] .= "$env=$ENV{$env},";
		}
		
		for (0..4){
			$outmsg[$_] =~ s/\n|\r/ /g;
			$outmsg[$_] =~ s/\|/ /g;
		}
		
		if ($ENV{'REMOTE_ADDR'}){
			$ip = $ENV{'REMOTE_ADDR'};
		}elsif ($ENV{'REMOTE_HOST'}){
			$ip = $ENV{'REMOTE_HOST'};
		}elsif ($ENV{'HTTP_CLIENT_IP'}){
			$ip = $ENV{'HTTP_CLIENT_IP'};
		}else{
			$ip = "Unknow";
		}
		(!$cfg{'cgierr_log_file'}) and ($cfg{'cgierr_log_file'} = './logs/cgierr.log');
		if (open (LOG, ">>$cfg{'cgierr_log_file'}")){;
			print LOG "$usr{'username'}|$outmsg[0]|$outmsg[1]|$outmsg[2]|$outmsg[3]|$outmsg[4]|$time|$date|$ip\n";
			close AUTH;
		}
	

	}else{
		print "<PRE>\n\nCGI ERROR\n==========================================\n";
					$sys_err[0]	and print "Error Message       : $sys_err[0]\n";
					$sys_err[1]	and print "Error Code          : $sys_err[1]\n";
					$sys_err[2]	and print "System Message      : $sys_err[2]\n";
					$0			and print "Script Location     : $0\n";
					$]			and print "Perl Version        : $]\n";
					$sid		and print "Session ID          : $sid\n";


		print "\nForm Variables IN\n-------------------------------------------\n";
		
		foreach $key (sort keys %in) {
			my $space = " " x (20 - length($key));
			$out_in .= "$key=$in{$key},";
			print "$key$space: $in{$key}\n";
		}
		
		print "\nForm Variables ERROR\n-------------------------------------------\n";
		foreach $key (sort keys %error) {
			my $space = " " x (20 - length($key));
			print "$key$space: $error{$key}\n";
		}
		
		print "\nEnvironment Variables\n-------------------------------------------\n";
		foreach $env (sort keys %ENV) {
			my $space = " " x (20 - length($env));
			$out_env .= "$env=$ENV{$env},";
			print "$env$space: $ENV{$env}\n";
		}
		
		print "\n</PRE>";

	}

	exit -1;
}